### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/labels#1]
- [x] add structure to the README.md
- [x] add standardised labels to this repo
- [x] research the GitHub [labels API](https://developer.github.com/v3/issues/labels/)
- [x] setup initial files

**Comment by nelsonic** [comment]
@jackcarlisle _thank you_ for creating the repo and this first issue. ❤️  ✅ 

please remember to add a time estimate _before_ assigning the story/task to yourself as per [step 5](https://github.com/dwyl/contributing/tree/095dc916dc2731edcd8b6af4f00b95f845c178ab#create-the-user-story-and-its-technical-tasks) to ensure that if it takes longer than your original estimate you are making notes to help others understand the complexity. 😉
