### ISSUE TITLE
`tech-debt` label

### ISSUE THREAD

**Issue by nelsonic** [dwyl/labels#101]
Sadly, on reviewing (_my own_) code, it's become clear to me that we have incurred some **technical debt**.
So proposing that we create a `tech-debt` label 

+ [x] Label name: **`tech-debt`**
+ [x] Description: "A feature/requirement implemented in a sub-optimal way & must be re-written."
+ [x] Color: `#FF3636` (a medium light shade of red) https://www.colorhexa.com/ff3636

> **Note**: We have a decent summary of **technical debt** in: https://github.com/dwyl/product-owner-guide#what-is-technical-debt

This issue is just about adding the label to our central repository so that new projects get it.
Anyone have an objection to me creating this label and the corresponding PR to add the detail to the `README.md`?

**Comment by iteles** [comment]
No objections to adding it.

Although choosing speed is the usual reason for tech debt, I've also seen it show up due to lack of experience or just laziness (choosing the _easy_ way rather than specifically a _fast_ way).
Is it worth changing the description to:

A feature/requirement is implemented in a sub-optimal way & must be re-written.

?

**Comment by nelsonic** [comment]
@iteles great points. How about:

"A feature/requirement implemented in a sub-optimal way & must be re-written." (removed the "is"...)

**Comment by iteles** [comment]
Perfect 👌

**Comment by nelsonic** [comment]
Label created: https://github.com/dwyl/labels/labels?page=2&sort=name-asc
![image](https://user-images.githubusercontent.com/194400/148361508-5a80a577-d57a-47dd-9fa0-a8dc017f7747.png)

Will add PR shortly.

**Comment by nelsonic** [comment]
@iteles you probably missed this notification: https://github.com/dwyl/labels/pull/100 📥  
Please review/merge when you can so that we don't have **`merge-conflicts`**.  🙏

**Comment by nelsonic** [comment]
@iteles once you've reviewed/merged Simon's PR #100 please see mine: https://github.com/dwyl/labels/pull/102 🙏

**Comment by nelsonic** [comment]
PR merged. ✅  (Thanks @iteles!)
