### ISSUE TITLE
"Labels already synced" (unable to re-sync labels)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/labels#103]
Using the Label Sync App: https://label-sync.herokuapp.com/
If a repo was previously synched - but doesn't have all the _latest_ labels - we aren't able to re-sync it to get the _latest_ labels ...
![image](https://user-images.githubusercontent.com/194400/151072494-ea36cd4c-a56b-4878-8882-e0a3d2cdcbee.png)

Seems like we will need to get a bit advanced in order to make this work ... 💭 

## Todo

+ [x] Migrate to Phoenix so this is maintainable #105 
+ [x] Update labels, colors and description on repo that has _previously_ had labels synched.

**Comment by nelsonic** [comment]
Basically, if the labels have _already_ been synced, we can no longer update them in add **`new`** labels. 💭

**Comment by nelsonic** [comment]
This is still painful ... 😿 
we need #104 / #105 🙏

**Comment by SimonLab** [comment]
This will be fixed with #109

**Comment by SimonLab** [comment]
This is now fixed at labels can be synchronized at https://labels.fly.dev/
