### ISSUE TITLE
Deploy application on Fly.io

### ISSUE THREAD

**Issue by SimonLab** [dwyl/labels#107]
The following PR #105 deploy the new Phoenix application automatically on Fly.io with
https://github.com/dwyl/labels/pull/105/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3

However we need a few more steps for the application to work:

- [x] Create a new Github oauth app (on dwyl org?) to have client id and and client secret values for production app
- [x] Add these two value as secrets on the Fly.io application, see https://fly.io/docs/flyctl/secrets-set/

@nelsonic I think only you have access to the Fly application, would it be easier to transfer the app to its own organisation so I can also have access to it and manage the secrets?

**Comment by nelsonic** [comment]
@SimonLab yeah, I have access to: https://labels.fly.dev > https://fly.io/apps/labels
![image](https://user-images.githubusercontent.com/194400/177260163-d2494eb6-b1d4-4cb4-9515-bd042d4c8367.png)
For some reason it was created as a "personal" app. 🙄 

Going to transfer to Org now and you will be Admin. ⏳

**Comment by nelsonic** [comment]
https://fly.io/docs/flyctl/apps-move/

```sh
flyctl apps move labels --org dwyl-labels
```

Please see: https://fly.io/dashboard/dwyl-labels/team (you have been invited)

**Comment by SimonLab** [comment]
Thanks @nelsonic I have access to the app now :+1:

**Comment by nelsonic** [comment]
@SimonLab thanks for confirming. ✅

**Comment by nelsonic** [comment]
@SimonLab FYI:

```sh
flyctl apps move labels-db --org dwyl-labels

INFO app "labels-db" is currently in organization "personal"
Moving an app between organizations requires a complete shutdown and restart. This will result in some app downtime.
If the app relies on other services within the current organization, it may not come back up in a healthy manner.
Please confirm whether you wish to restart this app now.
? Move app labels-db? Yes

successfully moved labels-db to dwyl-labels
```
