### ISSUE TITLE
Retire or Redirect Heroku Labels App to Fly.io ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/labels#110]
At present we have the **`Hapi.js`** version of the LabelSync App deployed to Heroku:  https://label-sync.herokuapp.com/

<img width="849" alt="image" src="https://user-images.githubusercontent.com/194400/177730816-7be0876f-8d9f-4fbc-9cb0-1fbc2893debe.png">

Several people have it bookmarked. 

The new version:  https://labels.fly.dev/
<img width="767" alt="image" src="https://user-images.githubusercontent.com/194400/177731067-407eaf3c-0a1c-47de-8fae-9b608c35be16.png">

We have access to the Heroku App: https://dashboard.heroku.com/apps/label-sync

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/194400/177731582-9f779bfc-ef47-4c00-b4d5-570a6dd5f9f4.png">

@SimonLab you have access: https://dashboard.heroku.com/apps/label-sync/access
<img width="1107" alt="heroku-label-sync-app-access" src="https://user-images.githubusercontent.com/194400/177732108-cddec3db-7b56-4112-9f70-aad03a59d686.png">

So if you want to just auto-deploy the ***`Phoenix`*** version to Heroku, that's an option.
The other option is to do a [**`301` Redirect**](https://moz.com/learn/seo/redirection) to the Fly.io App. 💭 

Please let us know your thoughts on this; what is your preference?

# Todo

+ [x] Discuss potential solutions (pls comment below)
+ [x] implement our preferred option 🤞

**Comment by SimonLab** [comment]
I think I would be tempted to add a redirect to the Fly application. I had a quick search and I don't think Heroku provide any DNS settings for this case and we have to do this via the nodejs server of the application. So we need to create a branch from the latest nodejs version of the application, add the redirect and deploy this branch to Heroku.

**Comment by nelsonic** [comment]
A more succinct `redirect.py`:
```python
#!/usr/bin/env python3

import sys
import os
from http.server import HTTPServer, BaseHTTPRequestHandler

class Redirect(BaseHTTPRequestHandler):
   def do_GET(self):
       self.send_response(301)
       self.send_header('Location', 'https://labels.fly.dev')
       self.end_headers()

HTTPServer(("", int(os.environ.get("PORT"))), Redirect).serve_forever()
```

Usage (`Procfile`):

```sh
worker: python redirect.py 
```

via: https://stackoverflow.com/a/47084250/1148249

**Comment by nelsonic** [comment]
@SimonLab yeah, the **`Hapi.js`** App is well and truly unusable at this point thanks to breaking changes. 🙄 

Please try _manually_ deploying the branch via: 
https://dashboard.heroku.com/apps/label-sync/deploy/github
<img width="914" alt="image" src="https://user-images.githubusercontent.com/194400/177744154-d8915380-49fd-4224-ad9a-13a793fe767f.png">

We should be able to upgrade from the "Cedar Stack" https://help.heroku.com/SMQ1J712/cedar-14-end-of-life-faq
If you run into issues, share screenshots + error messages in this thread so we can ref in future.

**Comment by SimonLab** [comment]
The error on https://github.com/dwyl/labels/issues/110#issuecomment-1177316950 was with a manual deploy
I can try to upgrade the heroku stack, otherwise we can delete this app (only @iteles can do this as owner) and create a new one with the Python redirect app shared above

**Comment by nelsonic** [comment]
@SimonLab noted. ✅ 

When you attempt to upgrade the stack: https://dashboard.heroku.com/apps/label-sync/settings
<img width="931" alt="image" src="https://user-images.githubusercontent.com/194400/177747060-f0fa4d3d-c93e-4cbe-a1f8-df1e2a5b3c22.png">

Does it let you?
This is what I see:

### "_heroku-22 will replace cedar-14 on the next deploy_"

<img width="960" alt="image" src="https://user-images.githubusercontent.com/194400/177747241-5c7baedd-d536-41cd-963c-a5b9c8345fec.png">

So if you try a _manual_ deploy now it _should_ work ... 🤞 💭

**Comment by nelsonic** [comment]
@SimonLab *confirmed* that redirect works. 👌🏻

UI/UX as it stands:
![6D20DCCC-B584-493B-AC5A-514F2DE00F40](https://user-images.githubusercontent.com/194400/177756760-c21359f1-cbdc-482b-962e-9994c4e7f3fa.jpeg)

Very happy that you’ve managed to get this working in Phoenix. 🎉
We can tighten the copy + interface in a follow-up issue+PR. 🤞

closing this issue as consider it resolved. 🎉

**Comment by nelsonic** [comment]
merci @SimonLab 🚀
