### ISSUE TITLE
Keep target owner/repo in form after sync

### ISSUE THREAD

**Issue by SimonLab** [dwyl/labels#111]
> The target repo gets removed from the form when the form is submitted.
see https://github.com/dwyl/labels/issues/108#issuecomment-1177254509

We might be able to use a Changeset combine with assigns/session to keep the target values in the form
We could also use LiveView to submit the form

**Comment by nelsonic** [comment]
@SimonLab not wanting to hijack this issue, I've created a separate one: https://github.com/dwyl/labels/issues/112
Recording the recently synched repos will make this task easier. 💭

**Comment by SimonLab** [comment]
https://github.com/dwyl/labels/issues/111#issuecomment-1177510220 this one is now done with #113 and #120 PRs.

Concerning keeping the name of the repos in the form after submitting it, this makes sense if the target (or source) repository is not found on Github, for example due to a typo in the names. However the labels are copied correctly we can clear the form and keep the source repo to copy the labels to another repository.

I think we can implement this feature using Elixir changeset with the form

**Comment by SimonLab** [comment]
It took me a bit more time than I thought to implement this feature as I tried first using Ecto with Schema and virtual fields combine with changeset to display the info on the form. However because the form is small I ended up just passing the form values directly to the view without using changeset, which make the code less complex that my first version

**Comment by SimonLab** [comment]
#126 is now merged
