### ISSUE TITLE
Record Synched Repos

### ISSUE THREAD

**Issue by nelsonic** [dwyl/labels#112]
My reading of [`/priv/repo/migrations`](https://github.com/dwyl/labels/tree/fc504036e2ec0b33007801d204ff153b64917a31/priv/repo/migrations) is that there are currently no DB tables for this App. 👀 💭 

## Story

**As a `person`** that syncs labels to _many_ projects ... 
<img width="1012" alt="dwyl-github-repos-365" src="https://user-images.githubusercontent.com/194400/177769099-18348af3-5e36-4ee7-856a-ea88a5f54425.png">
**I want** to ***`record`*** which **`repos`** have had their labels **synched**
**So that** I can easily:
a) Track which repos have been _recently_ synced
b) have a **`Re-Sync All Repos`** button that will let me schedule a task to re-sync _everything_ in one go.

> **Note**: we should _never_ store the GitHub Tokens in the DB or log them. 
Re-synching should always require re-auth. 

## Todo

+ [x] Create a migration that stores `person_id`, `owner` and `repo_name` in the `labels-db` (along with `timestamps()`
+ [x] Save this basic data whenever someone synchs
+ [x] _Deploy_! 🚀

**Comment by SimonLab** [comment]
The Github API /user endpoint returns a json containing the Github id of the user. We can use this value as the `person_id`, see https://docs.github.com/en/rest/users/users#get-the-authenticated-user

**Comment by nelsonic** [comment]
Indeed. GitHub UserId as person_id. 👌🏻

**Comment by SimonLab** [comment]
The "Todos" in https://github.com/dwyl/labels/issues/112#issue-1297322507 are now impleted with https://github.com/dwyl/labels/pull/113

I will create another PR for 
> have a Re-Sync All Repos button that will let me schedule a task to re-sync everything in one go.

as I need to have a bit more thought on how to do this nicely

**Comment by SimonLab** [comment]
#116 PR deployed
