### ISSUE TITLE
Deploy to Fly only when branch is merged

### ISSUE THREAD

**Issue by SimonLab** [dwyl/labels#122]
Currently as soon as a PR is open the action https://github.com/dwyl/labels/blob/main/.github/workflows/main.yml will try to deploy the PR to the Fly instance.
We want instead to deploy only when the branch is merged to main.
- [ ] Update the trigger for the action to be on push on the `main` branch, see https://github.com/orgs/community/discussions/26724#discussioncomment-3253093

see also Github doc for actions events: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters

**Comment by nelsonic** [comment]
Fixed by #123
