### ISSUE TITLE
Create the `flutter` label?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/labels#173]
Similar to the `elixir` label, I think we can add a `flutter` label to help us distinguish issues linked to the Flutter/Dart framework.
@nelsonic what do you think?

**Comment by nelsonic** [comment]
@SimonLab 100%. Please create. Use Firefox eye drop to color-pick the flutter logo for the label color. https://firefox-source-docs.mozilla.org/devtools-user/eyedropper/index.html

**Comment by SimonLab** [comment]
Done:
![image](https://user-images.githubusercontent.com/6057298/217513864-01ca30ed-6e3b-4e7d-8fad-a049b91a74a9.png)

**Comment by nelsonic** [comment]
Merci @SimonLab 👌
