### ISSUE TITLE
Fail to deploy with Phoenix 1.7

### ISSUE THREAD

**Issue by SimonLab** [dwyl/labels#184]
The lateset commit has updated phoenix to 1.7: https://github.com/dwyl/labels/commit/4cb8b195fc93754f60bea9042eded178ee20b9c8

However the deploy action is failing:
![image](https://user-images.githubusercontent.com/6057298/221926319-a4367b33-a715-4479-a863-2c4a38347024.png)
https://github.com/dwyl/labels/actions/runs/4288341974/jobs/7470241519

**Comment by nelsonic** [comment]
Thanks for opening. 👌

**Comment by nelsonic** [comment]
Glad this is working. Thanks @SimonLab & @LuchoTurtle 👌
