### ISSUE TITLE
Css styles broken

### ISSUE THREAD

**Issue by SimonLab** [dwyl/labels#189]
![image](https://user-images.githubusercontent.com/6057298/224998869-12483ad4-f983-4a41-8951-1e8b3caef309.png)

Merging the PR https://github.com/dwyl/labels/pull/185 broke the css style

**Comment by SimonLab** [comment]
There is also the following warning:
![image](https://user-images.githubusercontent.com/6057298/225021895-f2290047-d0a2-4b16-8f56-83de65022c02.png)

**Comment by nelsonic** [comment]
Thanks for fixing. 👌
