### ISSUE TITLE
chore label ? 

### ISSUE THREAD

**Issue by jrans** [dwyl/labels#37]
Can we add a chore label to the repo.

This could be applied to things like setup, configuring that have been done time and time again and require no new knowledge just known time.

My reason for this is sometimes if low on brain power these are things I can tackle to remain productive whilst also offload on to developers who have done their work or are not sure what to do.

**Comment by nelsonic** [comment]
@jrans _totally agree_. What _color_ should `chore` be...?
Pleas also add a _description_ of the label to the readme so people know when/how to use it.

**Comment by iteles** [comment]
Brown for chores?
http://www.color-hex.com/color/3a2716
<img width="527" alt="screen shot 2016-10-21 at 22 57 50" src="https://cloud.githubusercontent.com/assets/4185328/19613015/d8e1364e-97e1-11e6-84c8-bad1e648b2a0.png">

Is it too obvious? 💩 
😉

**Comment by nelsonic** [comment]
![do it](https://media.giphy.com/media/wi8Ez1mwRcKGI/giphy.gif)

**Comment by iteles** [comment]
👍
