### ISSUE TITLE
Add note to readme on syncing to a repo with existing issues 

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/labels#45]
I ❤️️ this and have already made use of it on a couple of new projects. 

My question is what happens when you sync to a repo that already has a bunch of issue (open & closed) with the older labels. 

Does the sync process delete other labels or just adds new one without touching the existing labels?

**Comment by iteles** [comment]
It doesn't touch the existing labels, just adds new ones or changes colours if they already exist (I'm pretty sure, but it's been a little while since I've gone through this code). Probably needs a note in the readme!

**Comment by nelsonic** [comment]
@sohilpandya if in doubt, read the `code`. 👀  😉 
The _desirable_ effect is as @iteles has _described_ to be _non-destructive_. 👍
