### ISSUE TITLE
`in-review` label: how and when to use it

### ISSUE THREAD

**Issue by nelsonic** [dwyl/labels#48]
The `in-review` label is _reserved_ for the team member / QA reviewing the Pull Request code/change. The _reviewer_ applies the label to _communicate_ with the rest of the team that they are _actively_ reviewing the PR and to avoid duplication of effort.
We _used_ to require reviewers to write a comment on the PR (_typically a 👀  `:eyes:` emoji_) to indicate that they were reviewing the PR, but we decided that using a label instead of a comment was clearer (_especially to non-technical team members/stakeholders_) and worked well for us.

> only the reviewer should apply the `in-review` label. this will start the clock on their Timer. 👍 

## Process Automation `enhancement` `help wanted`

Once the pull request has been merged @dwylbot 🤖  will remove the `in-review` label from the Pull Request and apply the `please-test` label. 🛎 
Additionally/Optionally @dwylbot 🤖  will _parse_ the commit messages in the PR for any issue numbers and apply the `please-test` label to those issues too. ✨

**Comment by iteles** [comment]
Is this the `in-review` label as used in the PRs?

On issues, teams have tended to move issues from `in-progress` to `in-review` once they have opened a PR on it, to ensure that they can easily identify what has already been worked on in the backlog and what still requires work. This might not be the best way of doing this, so I wanted to bring it up here to make sure the differentiation was able to be clarified.

**Comment by nelsonic** [comment]
When a _story_ is ***"code complete"*** by the Developer(s) they will _remove_ the `in-progress` label.
I would _suggest_ the _story_ gets the `awaiting-review` label applied. see: https://github.com/dwyl/labels/issues/49

_ideally_ the act of _assigning_ the PR to Reviewer(s) will do all the necessary label changing.

**Comment by iteles** [comment]
Perfect 👍

**Comment by iteles** [comment]
Note: I disagree that dwylbot should *automatically* apply a 'please test' label. Often there is a lag between a merge and a deployment and we've had POs complain before that things have been assigned to them prematurely (it just looks to them like the issues *hasn't been fixed*) which is an ineffective us of everyone's time.

**Comment by iteles** [comment]
@nelsonic Label added to repo and description [added to readme](https://github.com/dwyl/labels/blame/18039e87ef897d40f85454735f320828ac11331c/README.md#L76) with reference to this issue. Can we close it?
