### ISSUE TITLE
External Dependency Label Doesn't Merge?

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/labels#54]
Not sure why but it doesn't seem to carry over even when using the tool?

**Comment by iteles** [comment]
The labels app copies the labels from *this* repo and there *is l* no external-dependency label here. Want to turn this into a proposal for one?

I created the one in hq independently as I find t quite useful for admin but we'd need to validate the need to have it across ALL repos.

**Comment by iteles** [comment]
@markwilliamfirth This label has now been created (#55) and synced successfully to 2 repos already.

Could you please try it and see if we can close this?

**Comment by markwilliamfirth** [comment]
👍
