### ISSUE TITLE
External dependency label

### ISSUE THREAD

**Issue by iteles** [dwyl/labels#55]
Over the past 2 months, I've found I've had to create an `external-dependency` label for 4 projects.

I use it when we're waiting for things like VPN access from an organisation, waiting for copy from a client or an update from someone/org we've asked a question of (for example).

Linked to #54.

Shall we add this?

**Comment by katbow** [comment]
I've definitely needed this label! It would be a useful addition 👍

**Comment by iteles** [comment]
Done!

**Comment by iteles** [comment]
Closing this as label now added to repo and description added to readme.
