### ISSUE TITLE
Such a great explanation of WHY - add to readme?

### ISSUE THREAD

**Issue by iteles** [dwyl/labels#57]
Awesome explanation from @SimonLab  https://github.com/dwyl/dwylbot/issues/7#issuecomment-285008193, worth a reference from the readme?

**Comment by nelsonic** [comment]
Would be _really_ good to add this Explanation to the `README.md` for new people joining and need to understand things ...
@SimonLab given that you made the original insightful comment, want to create the PR? 💭
