### ISSUE TITLE
New undiscussed labels have appeared in this repo - why?

### ISSUE THREAD

**Issue by iteles** [dwyl/labels#58]
Does anyone know why there are a number of new labels that have been added [to this repo](https://github.com/dwyl/labels/labels) which have not been discussed anywhere in the issues or added to the readme?

<img width="172" alt="screen shot 2017-03-09 at 20 19 56" src="https://cloud.githubusercontent.com/assets/4185328/23769052/f5b2654a-0505-11e7-99c8-7be642407a11.png">
<img width="149" alt="screen shot 2017-03-09 at 20 19 44" src="https://cloud.githubusercontent.com/assets/4185328/23769051/f5b23796-0505-11e7-87b7-e0522329160d.png">

I recognise some of these as labels myself or @markwilliamfirth created as *[hq](https://github.com/dwyl/hq)-specific* labels but I don't think they are generically useful enough to belong in a list of labels that sit across [all projects](https://github.com/dwyl/labels#why).

**NOTE:** If no one has provided an answer or discussed the need to include them in this repo here within 1 week, I'll remove them until the need to have them is raised and validated 👍

**Comment by markwilliamfirth** [comment]
@iteles I synched the labels repo with hq because I thought it was out of date (when I was trying to sync labels to QS etc it wouldn't sync over blocker label etc) - feel free to revert

**Comment by nelsonic** [comment]
@iteles I think we just need to _clarify_ that the labels in https://github.com/dwyl/labels/labels are the ones that we think are _universally_ applicable to all our projects (_and those of our clients who are using our **GitHub Labels-based-Workflow**_) so `Phase2`, `blog` and `brand` will not be applicable to say "SafeLives" or "The Science Museum Group"... 😉

**Comment by markwilliamfirth** [comment]
Yeah this is my bad - I didn't realise that was the case, but I get it and it makes sense now

**Comment by markwilliamfirth** [comment]
Maybe we need an external labels repo and internal labels repo?

**Comment by nelsonic** [comment]
Yeah, that's a good idea. there are certain "Admin" or "Ops" related labels that we need to describe. 👍

**Comment by iteles** [comment]
Have removed these new labels from this repo 👍
