### ISSUE TITLE
Should you remove a 'question' label once the question has been answered?

### ISSUE THREAD

**Issue by Cleop** [dwyl/labels#62]
In instances like this one: https://github.com/research-resource/research_resource/issues/99#event-1016978800 ... where you ask a question and once it's answered there's no need for further discussion, should you remove the `question` label?

I remove the `in-progress` label once I've stopped working on something, it's a verb kind of label. However `question` is both a verb but also a bit like an adjective, it's saying, this issue is the variety where a question is getting asked and therefore by removing the `question` label perhaps you're making it less useful for people to search for in the future by category?

It's only relevant to search for `in-progress` issues whilst they're still in progress however are people still likely to search by `question` even once the question has been answered  or is it more useful for the team to know that the question has been attended to (as the question tag has been removed once the question has been answered)?

**Comment by nelsonic** [comment]
@Cleop the `question` label is _really_ useful for _finding_ questions later. 
If the `question` has been _answered_ it's still a question...
Also, there are instances where people _update_ the answer to questions months later.
In the same way that we are going to have a `help wanted` "_view_" in Tudo see: https://github.com/dwyl/tudo/issues/146 we will have a "FAQ" which will collate all questions across all repos so leaving the label on the issue will be _useful_. 👍
