### ISSUE TITLE
Unable to Sync to client project repo I have Admin Access to...

### ISSUE THREAD

**Issue by nelsonic** [dwyl/labels#63]
Hi @jackcarlisle hope your day is going well. (_I haven't forgotten your PRs don't worry, just working my way through the client project backlog ..._)
Would you mind taking a look at why we are unable to sync labels to a Client Project repo: https://github.com/OxfordAbstracts/oxabs-table-versions/labels
You should have access to investigate: https://github.com/OxfordAbstracts/oxabs-table-versions/invitations
perhaps get a second pair of eyes from @Conorc1000 if needed. 👍 
(_Thanks_!)

**Comment by iteles** [comment]
Yea, I had this the other day and had to manually go into an organisation's settings and grant access to labels as there's no warning that the labels failed - it gives a successful message. Not really sustainable.

**Comment by jackcarlisle** [comment]
@nelsonic @iteles sounds good I'll take a look now!

**Comment by jackcarlisle** [comment]
@nelsonic I deleted the project locally because to save space on my laptop. Therefore I can't run the project locally because I need the `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` for the labels project. Do you have access to them in your github developer applications?

**Comment by jackcarlisle** [comment]
@nelsonic remembered that they're on heroku!

**Comment by jackcarlisle** [comment]
@nelsonic I'll need the developer environment variables from the local version of the application as opposed to the ones for labels on heroku https://github.com/settings/connections/applications/ee8d97bb9fdb3dbf66b9 

I think @jrans has access to them

**Comment by jackcarlisle** [comment]
I've added proper error messages for when the application doesn't have the right permissions, and also for when the labels have already been synced. I tried to change the `scope` of the application but it can't alter labels for a `private` repo unless it specifically gives it the right permissions.

**Comment by nelsonic** [comment]
The _reason_ the label sync was failing for OxAbs was that the app was not enabled:
![image](https://cloud.githubusercontent.com/assets/194400/25219747/534e7a60-25a7-11e7-84b9-4a5987101844.png)

When I try to _logout_ of the LabelSync app and re-login again it doesn't ask me to authorise specific repos ...
so I _temporarily_ removed restrictions:
![image](https://cloud.githubusercontent.com/assets/194400/25219788/75c11cb0-25a7-11e7-81a2-8d3c5fc1929d.png)

And performed the Sync:
![image](https://cloud.githubusercontent.com/assets/194400/25219821/90b9169e-25a7-11e7-9912-7d317a731798.png)

Then re-enabled the restrictions so that the security isn't "_wide open_". 🔒

**Comment by iteles** [comment]
Yes, sorry I didn't make that very clear either, the issue is that the app doesn't request permissions to the repo when it needs them!

**Comment by nelsonic** [comment]
closing. thanks. 🎉

**Comment by iteles** [comment]
@nelsonic Why are we closing this? Is it not still an issue?

I imagine the resolution is a step to check whether the app has the correct permissions at the time of _sync_ rather than only once and up front and request the correct permissions if it doesn't have them?

**Comment by nelsonic** [comment]
@iteles it _probably_ is still an issue for _someone_ but not for me. 
If someone `else` raises this issue we can dedicate some dev time to fixing it. but for now, closed. ✅
