### ISSUE TITLE
Starter label - What is?

### ISSUE THREAD

**Issue by harrygfox** [dwyl/labels#66]
`[starter]`
here is a picture
![image](https://cloud.githubusercontent.com/assets/7805691/26002727/7b3dd75e-3728-11e7-9767-7eea60d76c50.png)

I couldn't find any description on the readme.

**Comment by nelsonic** [comment]
@harrygfox see: https://github.com/dwyl/labels/issues/36
(_Yes, we need to add a description to the readme..._) 👍
