### ISSUE TITLE
T4h - Stands for .. ?

### ISSUE THREAD

**Issue by edwardcodes** [dwyl/labels#67]
Hi! I usually use some labels but this one i have no idea what it means!
Thanks.

**Comment by SimonLab** [comment]
Hi @edwardcodes, the T4h tag is a time estimation for an issue. If applies it means that an issue will take around 4 hours to be completed.
On the readme there is this description "T[x]h #F7C6C7 - Estimated time in 'x' hours the issue will take to resolve", linked also to this issue

**Comment by edwardcodes** [comment]
Hi! @SimonLab Thank you!
