### ISSUE TITLE
Reference label?

### ISSUE THREAD

**Issue by harrygfox** [dwyl/labels#68]
Example usage from another repository
![image](https://cloud.githubusercontent.com/assets/7805691/26409686/2cf77b0c-4099-11e7-99e8-dd4f0703d32a.png)

I have found it very useful to be able to look up documented decisions, decision making processes, and schedules etc. I have also found it _appropriate_ to label things [like this](https://github.com/OxfordAbstracts/site/issues/3) as "Reference" because it is a ticket that says: Here is a feature request that **_won't be implemented yet_**.

Thoughts?

**Comment by iteles** [comment]
@harrygfox I come from the school of thought that these decisions should be documented in the documentation with reference to the issues where the discussion took place.
My view is that everyone - whether they are technical or not - has access to the documentation and issues are a little less accessible.

Do you see a situation where this might not be a good solution?

**Comment by harrygfox** [comment]
@iteles Honestly I was under the impression that we didn't use the Wiki section! 
I see what you mean about documentation being more accessible, but have operated under the assumption that "**everything** is in the issues" and that that's the line we give to clients etc.

**Comment by iteles** [comment]
@harrygfox We _don't_ use the wiki section - all of our documentation is in the `readme.md` files 😊 

This is actually a particular bug-bear of mine and comes from Founders & Coders which is that "everything _gets lost_ in the issues" and nothing is ever _codified into a _real_ **decision** in the documentation... 😳

**Comment by harrygfox** [comment]
AH! Interesting! Thanks, Ines
