### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by ghost** [dwyl/labels#69]
Tried to sync labels repo with summer repo and this happened

<img width="807" alt="screen shot 2017-05-31 at 14 25 35" src="https://cloud.githubusercontent.com/assets/5732209/26634009/22dc4a3e-460d-11e7-9264-1ab4ac9dcf28.png">

**Comment by jackcarlisle** [comment]
@markwilliamfirth did you check the logs on heroku?

**Comment by markwilliamfirth** [comment]
(Would someone be able to give me access?)

**Comment by nelsonic** [comment]
No longer an issue. closing.
