### ISSUE TITLE
Sync Failed - labels already synced?

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/labels#70]
Tried to sync labels repo to the print-me repo and this happened

<img width="424" alt="screen shot 2017-06-08 at 17 49 59" src="https://user-images.githubusercontent.com/5732209/26940544-ef9ba2de-4c72-11e7-8c09-1afb944d1019.png">

**Comment by iteles** [comment]
Crumbs, my comment failed 🙄 
I thought I'd written: I just looked through the `print-me` repo and it looks like all the labels are correct, in which case this would not be a bug. Could you please confirm why you think there's a bug?

**Comment by markwilliamfirth** [comment]
I know why

blocker label didn't sync, but it's because it isn't in the labels repo
