### ISSUE TITLE
Add a 'spike' label

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/labels#71]
I find spikes super useful and it would be really nice if the dwyl labels came with a spike label!

**Comment by nelsonic** [comment]
@iteles we _use_ a `spike` label on some projects, any objections to creating it here for _all_ projects? 
@ZooeyMiller we would need to have a _description_ of what a "spike" is ... do you have time to craft some copy? 😉

**Comment by ZooeyMiller** [comment]
@nelsonic Yep would be happy to write a little copy on what a spike is if the need is confirmed :smile:

**Comment by nelsonic** [comment]
@ZooeyMiller please write copy for what a spike is and post as comment thanks! 🎉

**Comment by iteles** [comment]
@nelsonic I've never actually used a spike 'label', I just make it part of the title of the issue, but no objections from me and if you're validating the label, happy to add one and see if people use it 👍 

@ZooeyMiller See https://github.com/dwyl/contributing/issues/34

**Comment by nelsonic** [comment]
@iteles, @shouston3 _just_ asked about the `spike` label ... 
could we create and define it...?

**Comment by nelsonic** [comment]
`spike` `#FB9414` label was added back in 2018 and we have used it a few times: https://github.com/dwyl/labels/labels
![image](https://user-images.githubusercontent.com/194400/119809037-9cf02b00-bedc-11eb-8faa-c7b2ca6a1db9.png)

Closing as "done". ✅
