### ISSUE TITLE
Clarification on enhancement v priority 5

### ISSUE THREAD

**Issue by Jbarget** [dwyl/labels#74]
priority-5 #C5DEF5 - lowest priority (non-urgent changes and backlog ideas)
enhancement #84B6EB - improving existing code

To me the word `enhancement` is better described as `non-urgent changes and backlog ideas` while `priority-5` is more to do about features that have been agreed and in-scope

Also does `improving existing code` mean refactoring? does it mean that its _only_ to do with code changes and not ideas?

**Comment by nelsonic** [comment]
@Jbarget _both_ good questions. 
`enhancement` is a bit "_vague_"... 
However I think `enhancement` is _useful_ to distinguish a feature that will improve the project/app.

Whereas  `Priority-5` is something that has been acknowledged as _valid_ idea/story,
but has been de-prioritised because it's are not particularly "_high value_" to end-users (_at present_)

(_I'm sure @iteles can put it more eloquently/succinctly..._)

**Comment by Jbarget** [comment]
thanks @nelsonic, the difference is still a bit ambiguous in my mind as I would have though everything on the backlog would improve the project

**Comment by iteles** [comment]
@jbarget It's about the validation really. 
A `priority-5` has been agreed by the product owner as something that _should_ be done or at least discussed again at a later date, but is quite low priority.

`enhancement` is usually used when something is more of an idea with nothing agreed around it.

You're definitely right, this is still ambiguous. Do you have any suggested wording that would help differentiate them?

**Comment by Jbarget** [comment]
I think as long as priority labels are only assigned to tasks for an active sprint and enhancement is only used when an idea or piece of functionality isn't to be included in the current sprint then that would make sense for me.

So, when a new sprint starts the Product Owner would see if any of the `enhancement` issues are relevant for the new sprint and if they are: remove `enhancement` and apply a priority label

Is that how it currently works?

**Comment by iteles** [comment]
@jbarget Not quite. A backlog has to be prioritised _prior_ to planning a sprint so priority labels are used by the Prosuct Owner to keep the backlog groomed. When you come to planning a sprint, the higher priorities should already be obvious. 

All priorities should be revised on a consistent basis, so if a PO sees something has been at p5 for a while without moving up the priority levels, it's a good indication that it either hasn't been validated by users or might no longer be relevant to the project

**Comment by Jbarget** [comment]
That makes sense, and am I right in thinking priority labels shouldn't really be adjusted mid-sprint unless new information/research shows something is more/less urgent?

**Comment by iteles** [comment]
@Jbarget Indeed!

**Comment by Jbarget** [comment]
👍
