### ISSUE TITLE
New label proposal | `Out of scope` label

### ISSUE THREAD

**Issue by iteles** [dwyl/labels#75]
Moved to this repo from: 
https://github.com/dwyl/tudo/issues/80

<img width="696" alt="screen shot 2017-07-29 at 12 33 31" src="https://user-images.githubusercontent.com/4185328/28744508-5b2db1a4-745a-11e7-86ea-83706d4b690e.png">

**Comment by iteles** [comment]
Since the original issue was created, I haven't felt a need for this label. To date I have just commented on the issue and allowed the Product Owner to follow up by closing the issue.

It would be cleaner when reviewing the closed issues and more likely useful for big collaborative open source project.

**Comment by nelsonic** [comment]
@iteles I _agree_. 
With a good _workflow_ we can easily "_train_" people to _focus_ on creating well-described issues
and then use Priority Labels to determine scope for a given sprint/project. 👍

**Comment by iteles** [comment]
:+1: Closing. Can be reopened if the need arises.
