### ISSUE TITLE
New label proposal | 'T2h'

### ISSUE THREAD

**Issue by iteles** [dwyl/labels#76]
As a developer working on dwyl projects I find that I often come across issues which will take more than 1 hour but less than half a day to complete. As such, I would like to have `T2h` label so that this can be applied to issues which I can tackle two of in a morning, for clarity.

There is an argument for asking people to break down their issues into no more than 1 hour time blocks before they start working on them, so I'm opening this as a discussion.

**Comment by nelsonic** [comment]
Do it. ⏳  2h 👍

**Comment by ZooeyMiller** [comment]
I'm very pro a T2h label, makes a lot of sense to me! Happy to add it in if we all think it's a good idea.

**Comment by iteles** [comment]
Done!
