### ISSUE TITLE
who "owns" the label-sync heroku app?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/labels#77]
Hi Jack! was just checking my Heroku dashboard and I don't _appear_ to have access to the `label-sync` app... could you please confirm that you've shared it with me? (_which email?_) thanks! 👍 

getting _failed_ sync:
![image](https://user-images.githubusercontent.com/194400/30436557-4da813f6-9964-11e7-8bed-ef3048eb92c8.png)

And want to try and debug it ... 🙄

**Comment by iteles** [comment]
Just looked in heroku and it's me. I'll transfer the ownership to your dwyl.io address now @nelsonic

**Comment by iteles** [comment]
Done:
<img width="733" alt="screen shot 2017-09-14 at 16 01 30" src="https://user-images.githubusercontent.com/4185328/30437375-5bae736c-9966-11e7-8d4f-9941030f8b17.png">

**Comment by nelsonic** [comment]
@iteles I don't _want_ to "_own_" it, I just want _access_ to it so I can _debug_. 
I "_own_" https://labels.herokuapp.com/ which is where the app was _meant_ to be deployed.
If _anything_ I will re-deploy the app to the more generic URL...
But for now I just want  to _understand_ why I'm seeing errors.
Thanks.

**Comment by iteles** [comment]
Redeploying to labels.herokuapp.com is a great idea 💡

**Comment by finnhodgkin** [comment]
I use this for basically every new repo I make and often forget the URL.

`labels.dwyl.com` is open :blush:

**Comment by nelsonic** [comment]
@iteles please grant access to the `label-sync` Heroku App to my "contact" gmail account. Thanks.

**Comment by nelsonic** [comment]
@iteles you've removed your assignment, but you haven't shared the App with the email address for my actual Heroku Account so I still see this:
![image](https://user-images.githubusercontent.com/194400/89056865-9c3a4700-d354-11ea-89b6-0bbde777a13f.png)

**Comment by iteles** [comment]
I appear to have misunderstood which email address you wanted me to share the app with and obviously shared with the wrong one. I will amend this now.

**Comment by iteles** [comment]
Amended @nelsonic 👍

**Comment by nelsonic** [comment]
New version deployed: #96 
(Thanks @iteles )

**Comment by iteles** [comment]
Perfect, thanks @nelsonic.

**Comment by nelsonic** [comment]
I see this banner message "_ines@... would like to transfer the app **label-sync** to you._" on _every_ Heroku page:
![ines-wants-to-transfer-label-sync](https://user-images.githubusercontent.com/194400/89614801-19961800-d87d-11ea-96c0-388b8fd590b3.png)

I din't ask to _own_ the App, I just wanted _access_ to it so that I could deploy/debug.
Owning the App would mean that it would consume _my_ "Free Dyno Hours" ... https://github.com/dwyl/email/issues/38
Which would _increase_ the likelihood of _all_ my demo apps being forced offline when those finite free hours are exhausted. 

Please don't be offended, but I am "rejecting" the request.

**Comment by nelsonic** [comment]
I see this banner message "_ines@... would like to transfer the app **label-sync** to you._" on _every_ Heroku page:
![ines-wants-to-transfer-label-sync](https://user-images.githubusercontent.com/194400/89614801-19961800-d87d-11ea-96c0-388b8fd590b3.png)

I din't ask to _own_ the App, I just wanted _access_ to it so that I could deploy/debug.
Owning the App would mean that it would consume _my_ "Free Dyno Hours" ... https://github.com/dwyl/email/issues/38
Which would _increase_ the likelihood of _all_ my demo apps being forced offline when those finite free hours are exhausted. 

Please don't be offended, but I am "rejecting" the request.
![reject-heroku-app-transfer](https://user-images.githubusercontent.com/194400/89617137-90cdab00-d881-11ea-8b6a-35de5dcfb02e.png)
