### ISSUE TITLE
Copy over inline descriptions for labels to new repos

### ISSUE THREAD

**Issue by iteles** [dwyl/labels#84]
Following on from #82, as an org admin,
I would like label-sync to not only copy over labels to my new repo, but also the inline descriptions,
So that there is no need to refer to the readme in the dwyl/labels repo to better understand them.

**Comment by ArsalaBangash** [comment]
I haven't tested it out because I haven't had the time to setup the repo locally, but I suspect this could be addressed by adding the description field to line 33 of lib/copy.js

```
body: { name: label.name, color: label.color, description: label.description }
```

I verified that the field in the API is called description: 

![image](https://user-images.githubusercontent.com/19757203/88501274-fcb63680-cf98-11ea-881c-84df9497b72b.png)

**Comment by ArsalaBangash** [comment]
@iteles Hi! Do you have any updates on this? This tool is pretty useful to me and my students, and I'd like to be able to copy over descriptions with it.

**Comment by nelsonic** [comment]
@ArsalaBangash thank you for showing and interest in this feature for the label sync tool
and for sharing that you and your students find it useful! 🎉 

As with all Open Source, contributions are always welcome, hence the **`help-wanted`** label on this issue. 💡 

@iteles I have made the required code change in PR https://github.com/dwyl/labels/pull/93

I added descriptions to all the labels in _this_ repo: https://github.com/dwyl/labels/labels (_please change as needed_)
![image](https://user-images.githubusercontent.com/194400/89026662-fe795480-d320-11ea-83d9-42d6b8109354.png)

And then used the _working_ App on my `localhost` to sync the labels to on of my personal repos:
<img width="693" alt="label-sync-success-localhost" src="https://user-images.githubusercontent.com/194400/89026718-17820580-d321-11ea-9c27-07f4f7ae81d5.png">

https://github.com/nelsonic/learn-music/labels

***Before***:
![nelsonic-learn-music-before-sync](https://user-images.githubusercontent.com/194400/89026754-28327b80-d321-11ea-92e2-2681a4777ad3.png)

***After***:
![nelsonic-learn-music-after-sync-with-label-descriptions](https://user-images.githubusercontent.com/194400/89026784-3385a700-d321-11ea-8f38-80e3042d9c50.png)

I don't have access to the Heroku App, see: https://github.com/dwyl/labels/issues/77 so I cannot test the update on Heroku.
Assigning this issue to you as I feel we can safely merge the PR without it breaking the Heroku App.

**Comment by nelsonic** [comment]
This feature is merged into `master` as part of #93 
but has not yet been deployed as per #95 (_build failed due to Node.js not being specified in `package.json`..._)
I'm working on #95 _now_ and will get the `label.description` deployed ASAP. ⏳

**Comment by nelsonic** [comment]
New version of app that copies `label.description` deployed. 🚀 
Now using:  https://label-sync.herokuapp.com
![image](https://user-images.githubusercontent.com/194400/89107536-94000b80-d429-11ea-8f4b-4a516617bbfc.png)

We can update the labels on a random throwaway project, e.g: https://github.com/nelsonic/rumbl/labels

**BEFORE**: 
![image](https://user-images.githubusercontent.com/194400/89107530-86e31c80-d429-11ea-9248-ddac5eef36c4.png)


***AFTER***:
![image](https://user-images.githubusercontent.com/194400/89107548-a37f5480-d429-11ea-8f66-dabf452b61ca.png)


@ArsalaBangash hope you and your team enjoy using the new version. 🙌

**Comment by ArsalaBangash** [comment]
Hi @nelsonic I thought of following up on this, and was very pleased to see that you guys merged this in!
