### ISSUE TITLE
Update Dependencies ...?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/labels#85]
https://david-dm.org/dwyl/labels
![image](https://user-images.githubusercontent.com/194400/41583676-247445c2-739d-11e8-96d7-7fcb3a3891d6.png)

> If anyone has **time** to help out with this, it would be good to update.
> The _main_ dependency is: https://github.com/dwyl/hapi-auth-github
> Which in turn has `zero` dependencies, so just needs to be "updated" to Hapi v17.

## Context 

I visited the repo hoping to do a _quick label sync_ to an "old" GitHub project that didn't have any of the newer labels ... 

When I was _greeted_ with the following warning message:
![image](https://user-images.githubusercontent.com/194400/41566516-b26aca58-7353-11e8-8e29-585a2804fe3a.png)

But when I click the link i'm given exactly ***zero insight*** into _which_ dependency has the vulnerability!!

**Comment by nelsonic** [comment]
Tests fail due to breaking change in `shot` dependency: #92

**Comment by SimonLab** [comment]
Dependabot has already been added
