### ISSUE TITLE
needs-ui (New Label Suggestion)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/labels#89]
During our standup today, we discussed an issue that was created in our App backlog: https://github.com/dwyl/app/issues/243 <sup>1</sup>

What we need is a way of _communicating_ to the team that an idea is _good_ but it needs more detail. _Specifically_ an idea that involves a strong _visual_ component should be accompanied by a ***sketch*** or ***wireframe*** _explaining_ how the idea/feature could be presented to and interacted with by "end users".

Hence the suggestion that a label **`needs-ui`** be applied to an issue that is at the ***idea*** stage that still needs some UI/UX to help communicate the idea more effectively.

> <sup>1</sup>The issue in question relates to "Gamification" and is an _excellent_ feature idea that we should _definitely_ explore further, but it has only been described _textually_ so it's not really ready to be estimated or prioritised ... it's needs more work to be ["ready for development"](https://github.com/dwyl/contributing/issues/109) ...
This reminded me that we need a way of way of determining the "_valuation_" of an issue and communicating to people that a _text-only_ feature/idea is of (_relatively_) low value in the product development lifecycle (_and may even be **distracting**_) to the users/team/company if it does not have an accompanying UI/UX implementation idea ... i.e. feature ideas without wireframes are ***incomplete***!
See: https://github.com/nelsonic/nelsonic.github.io/issues/756

Related to: https://github.com/dwyl/app/issues/239

**Comment by ArsalaBangash** [comment]
I use the Status category in [my org's labels](https://github.com/grey-software/github-labels/labels), and I think Status: Needs UI makes sense as a label. Feature ideas without wireframes are indeed incomplete!

**Comment by nelsonic** [comment]
@ArsalaBangash thanks for reminding us that we should just _create_ the label. 
https://github.com/dwyl/labels/labels
![needs-ui-label-created](https://user-images.githubusercontent.com/194400/88527025-9ced7900-cff4-11ea-8d55-be8583a54832.png)
