### ISSUE TITLE
Draw inspiration from my org's Github labels

### ISSUE THREAD

**Issue by ArsalaBangash** [dwyl/labels#90]
Hi DWYL, I love what your org is doing, and I've used your label syncing tool to sync labels across my org's repos. 

This is the repo where I maintain my labels: https://github.com/grey-software/github-labels/labels

If you find them useful, I'd appreciate some help raising awareness for my org so that I can get backing from a fiscal host.

**Comment by nelsonic** [comment]
Hi @ArsalaBangash thanks for sharing a link to your labels. 🔗 
They look good and we're sure they work well for your org. 👍 
Closing this issue as there is no further action we can take on it.
